logging.file: logs/application.log
logging:
  level:
    org:
      springframework:
        web: OFF
      hibernate: OFF
    root: OFF
spring:
  datasource:
    url:  jdbc:h2:file:./h2/binluis
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
