logging.file: logs/application.log
logging:
  level:
    org:
      springframework:
        web: ERROR
        core: ERROR
        beans: ERROR
        context: ERROR
        transaction: ERROR
      hibernate: DEBUG
spring:
  datasource:
    url:  jdbc:h2:file:./h2/binluis
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
